counter
Yuliana-coder/react-hw3 pull request #1
Opened 2021-10-06 12:13 UTC by Yuliana-coder

Компонент Counter, в котором два поля с счетчиками, второй из которых начинает отсчет с 10. После обновления страницы счетчик начинает считать снова.
МО5-116б Антипина Юлиана

2021-10-09 16:14 UTC, dshuran requested changes

2021-10-09 16:14 UTC, dshuran commented on src/App.js
> +        <Counter countersTitile={countersTitile} />
Смысл данного домашнего задания заключался в том, чтобы создать два инстанса одного компонента. Вы же всё сделали в рамках одного компонента Counter. В этом мало смысла, так можно всё сразу внутри App было написать, а мы хотим переиспользовать счётчик :)

2021-10-09 16:14 UTC, dshuran commented on src/App.js
> +  let countersTitile = {
Наверно, не Titile, а title, и везде нужно поправить

2021-10-09 16:14 UTC, dshuran commented on src/components/counter/counter.jsx
> +            startCount: 10,
Непонятно, зачем startCount нужен в state. Он должен быть в props. Мы его вообще никак не меняем, поэтому он не является состоянием данного компонента.

2021-10-09 16:14 UTC, dshuran commented on src/components/counter/counter.jsx
> +    componentWillUmount() {
Опечатка в названии метода. При удалении данного компонента раньше времени отсчёт будет идти вечно. Нужно componentWillUnmount

2021-10-09 19:14 UTC, Yuliana-coder commented on src/App.js
> +        <Counter countersTitile={countersTitile} />
Неправильно поняла задание, исправила, надеюсь теперь верно

2021-10-09 19:19 UTC, Yuliana-coder commented on src/components/counter/counter.jsx
> +    componentWillUmount() {
Поправила, но там же вроде бы componentDidMount должен счетчик запускать? Если я верно поняла. То есть страница загрузилась, счетчик считает, как досчитал, сбрасываем сетинтервал. Затем, когда страницу обновляем все заново - верно?

2021-10-09 19:20 UTC, Yuliana-coder commented on src/components/counter/counter.jsx
> +            startCount: 10,
Иправила

2021-10-17 12:18 UTC, dshuran approved these changes

2021-10-17 12:18 UTC, merged